"""Readiness vocabulary; no implied approval or automatic state promotion."""
from enum import Enum


class Readiness(str, Enum):
    PACKAGE_READY = 'PACKAGE_READY'
    PROJECT_CONFIG_READY = 'PROJECT_CONFIG_READY'
    PROJECT_FOUNDATION_READY = 'PROJECT_FOUNDATION_READY'
    CAPABILITY_READY = 'CAPABILITY_READY'
    FEATURE_READY = 'FEATURE_READY'
    READY_FOR_TEST = 'READY_FOR_TEST'
    EXECUTION_READY = 'EXECUTION_READY'
    READY_FOR_RETEST = 'READY_FOR_RETEST'
    VERIFIED = 'VERIFIED'
