"""Bounded owner-specific semantic producers; no scanning, publication or approval.

Observations are explicit caller interpretations of exact evidence, not a code
parser or an LLM. Host callbacks authenticate authority; generated bytes do not.
"""
import copy
import hashlib
import json

from shared.sdlc.foundation.contract import _approval, validate_manifest
from shared.sdlc.foundation.profiles import PROJECT_FOUNDATION_PROFILE_ARC42_V1 as PROFILE
from shared.sdlc.foundation.inventory import classify
from shared.sdlc.foundation.workflow import _declared_ref, exact_ref, semantic_bytes, SECTION_DOMAINS, SEMANTIC_OWNERS
from shared.sdlc.policy.contract import validate_policy
from shared.sdlc.schema import (REFERENCE, STRING, VERSION, identifier, object_schema,
                                read_document, reject_secrets, unique, validate_reference, validate_schema)
from shared.sdlc.topology.contract import validate_topology

PRODUCERS = {
    'domain-discovery': ('BA', ('product_goals', 'glossary', 'actors', 'entities', 'lifecycle', 'business_rule', 'gaps')),
    'architecture-discovery': ('ENGINEERING', ('constraints', 'context_scope', 'solution_strategy',
        'architecture_pattern', 'building_blocks', 'runtime', 'deployment', 'crosscutting',
        'quality_facts', 'risks', 'decisions_inventory', 'historical_rationale', 'gaps')),
    'test-foundation': ('TEST', ('test_levels', 'ownership', 'test_split', 'execution_topology',
        'fixtures_data', 'quality_gates', 'evidence_expectations', 'automation_role', 'gaps')),
    'adr-management': ('ENGINEERING', ('context', 'decision', 'rationale', 'consequences', 'alternative', 'gaps')),
    'c4-modeling': ('ENGINEERING', ('c4_element', 'c4_relationship')),
}
LABELS = {'OBSERVED': 'CURRENT_SYSTEM', 'INFERRED': 'INFERRED', 'AUTHORITY': 'CONFIRMED',
          'DECISION_EVIDENCE': 'CURRENT_SYSTEM', 'PROPOSED': 'PROPOSED', 'UNKNOWN': 'UNKNOWN',
          'DEFERRED': 'DEFERRED', 'APPROVED_TARGET': 'APPROVED_TARGET'}
def enum(values):
    return {'type': 'string', 'enum': tuple(values)}


ENUM = enum
REFS = {'type': 'array', 'items': REFERENCE}
QUESTIONS = {'type': 'array', 'items': STRING}
OBSERVATION_V1 = object_schema({'id': STRING, 'topic': STRING, 'statement': STRING,
    'basis': ENUM(LABELS), 'references': REFS, 'status': ENUM(PROFILE['statuses']), 'questions': QUESTIONS})
RECORD_V1 = object_schema({**OBSERVATION_V1['properties'], 'owner': ENUM(('BA', 'ENGINEERING', 'TEST')),
    'evidence_label': ENUM(LABELS.values()), 'source_producer': ENUM(PRODUCERS)})
BASE_FIELDS = {'schema_version': VERSION, 'id': STRING, 'revision': STRING,
    'topology_ref': REFERENCE, 'project_policy_ref': REFERENCE,
    'mode': ENUM(PROFILE['evidence_by_mode']), 'artifact_class': ENUM(('RUNTIME',)),
    'source_producer': ENUM(PRODUCERS), 'owner': ENUM(('BA', 'ENGINEERING', 'TEST')),
    'records': {'type': 'array', 'items': RECORD_V1}}
ELEMENT_V1 = object_schema({'record_id': STRING,
    'kind': ENUM(('ACTOR', 'EXTERNAL_SYSTEM', 'SYSTEM', 'CONTAINER', 'COMPONENT', 'DEPLOYMENT_NODE', 'INSTANCE')),
    'parent': STRING}, optional=('parent',))
RELATIONSHIP_V1 = object_schema({'record_id': STRING, 'source': STRING, 'target': STRING,
                               'level': ENUM(('CONTEXT', 'CONTAINER', 'COMPONENT', 'DEPLOYMENT'))})


def _schema(producer):
    fields = dict(BASE_FIELDS)
    if producer == 'test-foundation': fields['automation_repository_role'] = STRING
    if producer == 'adr-management':
        fields['decision_status'] = ENUM(('RECOVERED_CURRENT_SYSTEM', 'PROPOSED', 'APPROVED_TARGET'))
    if producer == 'c4-modeling':
        fields.update(elements={'type': 'array', 'items': ELEMENT_V1, 'minItems': 1},
                      relationships={'type': 'array', 'items': RELATIONSHIP_V1})
    return object_schema(fields)


def _domain(producer, topic):
    if producer == 'domain-discovery': return 'product' if topic == 'product_goals' else 'domain'
    return 'testing' if producer == 'test-foundation' else 'architecture'


def _config(topology, policy):
    validate_topology(topology); validate_policy(policy)


def _configuration_refs(root, topology, policy, revision):
    _config(topology, policy)
    refs = {'topology_ref': exact_ref(root, '.sdlc/topology.json', revision),
            'project_policy_ref': exact_ref(root, '.sdlc/project-policy.yml', revision)}
    _validate_configuration(refs, root, topology, policy)
    return refs


def _validate_configuration(data, root, topology, policy):
    for key, expected, path in (('topology_ref', topology, '.sdlc/topology.json'),
                                ('project_policy_ref', policy, '.sdlc/project-policy.yml')):
        ref = data[key]
        if ref['path'] != path: raise ValueError('canonical Foundation configuration reference required')
        source = validate_reference(ref, root, revision=True)
        if read_document(source.read_text(encoding='utf-8')) != expected:
            raise ValueError('supplied topology/Project Policy snapshot drift')


def _bound_approval(data, root, topology, policy, context):
    """Reuse exact enclosing Foundation approval; never invent a receipt shape.

    An APPROVED_TARGET section must contain the exact complete producer snapshot.
    Section approval of unrelated architecture prose does not approve this ADR.
    """
    required = {'manifest', 'approval', 'human_actor_authenticator'}
    if (not isinstance(context, dict) or not required <= set(context)
            or set(context) - required - {'previous'}):
        raise ValueError('APPROVED_TARGET requires exact enclosing Foundation approval binding')
    manifest = validate_manifest(context['manifest'])
    if manifest['authority'] != SEMANTIC_OWNERS or manifest['mode'] != data['mode']:
        raise ValueError('enclosing Foundation owner/mode mismatch')
    for domain, ref in manifest['entry_points'].items():
        if ref['path'] != policy['authority'].get(domain): raise ValueError('policy authority mismatch')
        _declared_ref(root, topology, ref)
    matched = False
    for name, section in manifest['sections'].items():
        if section['owner'] != SEMANTIC_OWNERS[SECTION_DOMAINS[name]]:
            raise ValueError('Foundation section ownership drift')
        for ref in section['references']:
            path = _declared_ref(root, topology, ref)
            if (section['evidence'] == 'APPROVED_TARGET' and section['owner'] == data['owner']
                    and ref['revision'] == data['revision']
                    and ref['sha256'] == hashlib.sha256(semantic_bytes(data)).hexdigest()
                    and path.read_bytes() == semantic_bytes(data)):
                matched = True
    if not matched: raise ValueError('approval must explicitly contain exact semantic artifact snapshot')
    previous = context.get('previous')
    if previous is not None:
        validate_manifest(previous)
        for ref in previous['entry_points'].values(): _declared_ref(root, topology, ref)
        for section in previous['sections'].values():
            for ref in section['references']: _declared_ref(root, topology, ref)
    _approval(manifest, root, context['approval'], context['human_actor_authenticator'], previous)


def validate_artifact(data, root, topology, policy, *, authority_authenticator=None, approval_context=None):
    """Revalidate schema, semantics, ownership, refs and host gates on every use."""
    _config(topology, policy)
    if (not isinstance(data, dict) or not isinstance(data.get('source_producer'), str)
            or data['source_producer'] not in PRODUCERS):
        raise ValueError('unsupported semantic producer')
    producer = data['source_producer']
    validate_schema(data, _schema(producer)); reject_secrets(data)
    _validate_configuration(data, root, topology, policy)
    identifier(data['id']); identifier(data['revision'])
    owner, topics = PRODUCERS[producer]
    if data['owner'] != owner: raise ValueError('producer owner cannot be reassigned')
    unique([row['id'] for row in data['records']], 'semantic statement id')
    seen_topics = set()
    for row in data['records']:
        identifier(row['id'])
        if row['id'].upper().startswith(('BR-', 'FR-', 'BAREF')):
            raise ValueError('producer statement IDs cannot create canonical business identities')
        if row['owner'] != owner or row['source_producer'] != producer or row['topic'] not in topics:
            raise ValueError('semantic ownership/topic/source mismatch')
        seen_topics.add(row['topic'])
        label = LABELS[row['basis']]
        if row['evidence_label'] != label or label not in PROFILE['evidence_by_mode'][data['mode']]:
            raise ValueError('basis/evidence label/mode mismatch')
        if label not in ('UNKNOWN', 'PROPOSED') and not row['references']:
            raise ValueError('factual semantics require exact evidence references')
        if row['status'] == 'COMPLETE' and (label in ('UNKNOWN', 'DEFERRED') or not row['references']):
            raise ValueError('COMPLETE requires known referenced evidence')
        if label == 'UNKNOWN' and not row['questions']:
            raise ValueError('UNKNOWN requires an explicit open question')
        unique([ref['path'] for ref in row['references']], 'semantic evidence reference')
        for ref in row['references']:
            _declared_ref(root, topology, ref)
            if row['basis'] == 'DECISION_EVIDENCE' and classify(ref['path'], policy)[2] in ('CODE', 'CONFIG'):
                raise ValueError('technology/config presence is not historical decision evidence')
            if label == 'CONFIRMED':
                domain = _domain(producer, row['topic'])
                if (ref['path'] != policy['authority'][domain] or not callable(authority_authenticator)
                        or authority_authenticator(domain, copy.deepcopy(ref)) is not True):
                    raise ValueError('CONFIRMED requires trusted exact policy authority authentication')
        if row['topic'] == 'architecture_pattern' and row['basis'] not in ('INFERRED', 'AUTHORITY', 'PROPOSED', 'APPROVED_TARGET', 'UNKNOWN', 'DEFERRED'):
            raise ValueError('architectural pattern interpretation must remain INFERRED')
        if row['topic'] in ('historical_rationale', 'rationale') and row['basis'] == 'INFERRED':
            raise ValueError('historical rationale cannot be inferred')
        if row['basis'] == 'DECISION_EVIDENCE' and row['topic'] not in ('historical_rationale', 'rationale', 'alternative', 'context', 'decision', 'consequences'):
            raise ValueError('decision evidence basis is restricted to explicit decisions')
        if row['topic'] == 'historical_rationale' and row['basis'] not in ('UNKNOWN', 'DECISION_EVIDENCE', 'AUTHORITY'):
            raise ValueError('historical rationale requires exact decision evidence or UNKNOWN')
    if producer not in ('c4-modeling', 'adr-management') and set(topics) - seen_topics:
        raise ValueError('producer coverage missing explicit gaps')
    if producer == 'test-foundation' and data['automation_repository_role'] != policy['testing']['automation_repository_role']:
        raise ValueError('automation repository role must come from Project Policy')
    if producer == 'adr-management': _validate_adr(data)
    if producer == 'c4-modeling': _validate_c4(data)
    if any(row['evidence_label'] == 'APPROVED_TARGET' for row in data['records']):
        _bound_approval(data, root, topology, policy, approval_context)
    return data


def _assemble(producer, artifact_id, revision, mode, observations, *, required=None):
    """Internal assembly only. Public outputs always pass validate_artifact."""
    if producer not in PRODUCERS: raise ValueError('unsupported semantic producer')
    validate_schema(observations, {'type': 'array', 'items': OBSERVATION_V1}); reject_secrets(observations)
    owner, topics = PRODUCERS[producer]
    records = []
    for observation in observations:
        row = copy.deepcopy(observation)
        row.update(owner=owner, source_producer=producer, evidence_label=LABELS[row['basis']])
        records.append(row)
    for topic in (topics if required is None else required):
        if not any(row['topic'] == topic for row in records):
            records.append({'id': 'unknown-' + topic.replace('_', '-'), 'owner': owner,
                'topic': topic, 'statement': 'UNKNOWN', 'basis': 'UNKNOWN', 'evidence_label': 'UNKNOWN',
                'references': [], 'status': 'UNKNOWN', 'source_producer': producer,
                'questions': ['What evidence establishes ' + topic.replace('_', ' ') + '?']})
    return {'schema_version': 1, 'id': artifact_id, 'revision': revision, 'mode': mode,
            'artifact_class': 'RUNTIME', 'source_producer': producer, 'owner': owner,
            'records': sorted(records, key=lambda row: row['id'])}


def produce(root, topology, policy, producer, artifact_id, revision, mode, observations, **gates):
    """Normalize explicit owner observations; return candidate records and gaps.

    No filesystem writes, implicit source reads, FR/BR, feature designs or cases.
    Even authenticated records stay RUNTIME until separate owner publication.
    """
    if producer not in ('domain-discovery', 'architecture-discovery', 'test-foundation'):
        raise ValueError('use the structured C4/ADR entry point')
    data = _assemble(producer, artifact_id, revision, mode, observations)
    data.update(_configuration_refs(root, topology, policy, revision))
    if producer == 'test-foundation':
        _config(topology, policy)
        data['automation_repository_role'] = policy['testing']['automation_repository_role']
    return validate_artifact(data, root, topology, policy, **gates)


def _validate_adr(data):
    rows = data['records']
    for topic in ('context', 'decision', 'rationale', 'consequences', 'gaps'):
        if sum(row['topic'] == topic for row in rows) != 1:
            raise ValueError('ADR requires one record for each semantic field')
    decision = next(row for row in rows if row['topic'] == 'decision')
    status = data['decision_status']
    if status == 'RECOVERED_CURRENT_SYSTEM':
        if decision['evidence_label'] not in ('CURRENT_SYSTEM', 'CONFIRMED'):
            raise ValueError('recovered ADR requires observed current decision')
        for row in rows:
            if row['topic'] in ('rationale', 'alternative') and row['basis'] not in ('UNKNOWN', 'DECISION_EVIDENCE', 'AUTHORITY'):
                raise ValueError('recovered rationale/alternatives require explicit decision evidence')
    elif status == 'PROPOSED' and decision['evidence_label'] != 'PROPOSED':
        raise ValueError('new ADR decision must remain PROPOSED')
    elif status == 'APPROVED_TARGET' and decision['evidence_label'] != 'APPROVED_TARGET':
        raise ValueError('approved ADR requires approved exact decision')


def adr(root, topology, policy, artifact_id, revision, mode, kind, observations, **gates):
    if kind not in ('RECOVERED', 'PROPOSED', 'APPROVED_TARGET'): raise ValueError('unsupported ADR kind')
    data = _assemble('adr-management', artifact_id, revision, mode, observations,
                     required=('context', 'decision', 'rationale', 'consequences', 'gaps'))
    data.update(_configuration_refs(root, topology, policy, revision))
    data['decision_status'] = 'RECOVERED_CURRENT_SYSTEM' if kind == 'RECOVERED' else kind
    return validate_artifact(data, root, topology, policy, **gates)


def _validate_c4(data):
    elements, relationships = data['elements'], data['relationships']
    ids = [row['record_id'] for row in elements + relationships]
    unique(ids, 'C4 id')
    records = {row['id']: row for row in data['records']}
    if set(ids) != set(records): raise ValueError('C4 semantic records must be used exactly once')
    nodes = {row['record_id']: row for row in elements}
    if any(node.get('parent') is not None and node['parent'] not in nodes for node in elements):
        raise ValueError('C4 parent must exist')
    systems = [row for row in elements if row['kind'] == 'SYSTEM']
    if len(systems) != 1 or not any(row['kind'] == 'CONTAINER' for row in elements):
        raise ValueError('C4 defaults require one owned System and a Container')
    connected = set()
    parent_kinds = {'CONTAINER': ('SYSTEM',), 'COMPONENT': ('CONTAINER',),
                    'INSTANCE': ('DEPLOYMENT_NODE',), 'DEPLOYMENT_NODE': ('DEPLOYMENT_NODE',)}
    for node in elements:
        if records[node['record_id']]['topic'] != 'c4_element': raise ValueError('C4 element record topic mismatch')
        parent = node.get('parent')
        if node['kind'] in ('CONTAINER', 'COMPONENT', 'INSTANCE') and parent is None:
            raise ValueError('owned C4 elements require parent')
        if parent is not None:
            if parent not in nodes or nodes[parent]['kind'] not in parent_kinds.get(node['kind'], ()):
                raise ValueError('invalid C4 parent ownership')
            ancestors = {node['record_id']}
            current = node
            while 'parent' in current:
                current = nodes[current['parent']]
                if current['record_id'] in ancestors: raise ValueError('cyclic C4 parent')
                ancestors.add(current['record_id'])
    level_kinds = {'CONTEXT': {'ACTOR', 'EXTERNAL_SYSTEM', 'SYSTEM'},
                   'CONTAINER': {'ACTOR', 'EXTERNAL_SYSTEM', 'CONTAINER'},
                   'COMPONENT': {'ACTOR', 'EXTERNAL_SYSTEM', 'CONTAINER', 'COMPONENT'},
                   'DEPLOYMENT': {'DEPLOYMENT_NODE', 'INSTANCE'}}
    edges = set()
    for relation in relationships:
        if records[relation['record_id']]['topic'] != 'c4_relationship': raise ValueError('C4 relationship record topic mismatch')
        source, target, level = relation['source'], relation['target'], relation['level']
        if source not in nodes or target not in nodes or source == target:
            raise ValueError('C4 relationship endpoints must exist and differ')
        if any(nodes[node]['kind'] not in level_kinds[level] for node in (source, target)):
            raise ValueError('C4 endpoint level mismatch')
        edge = (source, target, level)
        if edge in edges: raise ValueError('duplicate C4 relationship')
        edges.add(edge); connected.update((source, target))
    if set(nodes) - connected: raise ValueError('orphan C4 elements need explicit relationships')


def c4_model(root, topology, policy, artifact_id, revision, mode, elements, relationships, **gates):
    validate_schema(elements, {'type': 'array', 'items': object_schema({
        'record': OBSERVATION_V1, 'kind': ELEMENT_V1['properties']['kind'], 'parent': STRING}, optional=('parent',))})
    validate_schema(relationships, {'type': 'array', 'items': object_schema({
        'record': OBSERVATION_V1, **{k: v for k, v in RELATIONSHIP_V1['properties'].items() if k != 'record_id'}})})
    data = _assemble('c4-modeling', artifact_id, revision, mode,
                     [row['record'] for row in elements + relationships], required=())
    data.update(_configuration_refs(root, topology, policy, revision))
    for key, rows in (('elements', elements), ('relationships', relationships)):
        data[key] = sorted([{'record_id': row['record']['id'], **{k: v for k, v in row.items() if k != 'record'}}
                            for row in rows], key=lambda row: row['record_id'])
    return validate_artifact(data, root, topology, policy, **gates)


def _view(kind, data, content, **extra):
    return {'schema_version': 1, 'artifact_class': 'DERIVED', 'projection': kind,
            'semantic_sha256': hashlib.sha256(semantic_bytes(data)).hexdigest(), 'content': content, **extra}


def render_c4(data, root, topology, policy, **gates):
    validate_artifact(data, root, topology, policy, **gates)
    if data['source_producer'] != 'c4-modeling': raise ValueError('structured C4 model required')
    records = {row['id']: row for row in data['records']}
    lines = ['%% DERIVED C4 projection; no authority or approval', 'flowchart LR']
    ids = {node['record_id']: 'n' + str(i) for i, node in enumerate(sorted(data['elements'], key=lambda x: x['record_id']))}
    def label(text):
        # Encode every user-controlled character so Mermaid cannot interpret syntax.
        return ''.join('#' + str(ord(char)) + ';' for char in text)
    for node in sorted(data['elements'], key=lambda x: x['record_id']):
        row = records[node['record_id']]
        lines.append(f'  {ids[row["id"]]}["{label(node["kind"] + ": " + row["statement"] + " [" + row["evidence_label"] + "]")}"]')
    for edge in sorted(data['relationships'], key=lambda x: x['record_id']):
        row = records[edge['record_id']]
        lines.append(f'  {ids[edge["source"]]} -->|"{label(edge["level"] + ": " + row["statement"] + " [" + row["evidence_label"] + "]")}"| {ids[edge["target"]]}')
    return _view('C4_MERMAID', data, '\n'.join(lines) + '\n')


ARC42_TOPICS = {
    'product_goals': 'introduction_goals', 'constraints': 'constraints',
    'actors': 'context_scope', 'entities': 'context_scope', 'lifecycle': 'context_scope',
    'context_scope': 'context_scope', 'solution_strategy': 'solution_strategy',
    'architecture_pattern': 'solution_strategy', 'building_blocks': 'building_block_view',
    'runtime': 'runtime_view', 'deployment': 'deployment_view', 'crosscutting': 'crosscutting_concepts',
    'decisions_inventory': 'architecture_decisions', 'historical_rationale': 'architecture_decisions',
    'quality_facts': 'quality_requirements', 'risks': 'risks_technical_debt', 'glossary': 'glossary',
    **{topic: 'quality_requirements' for topic in PRODUCERS['test-foundation'][1] if topic != 'gaps'},
}


def arc42(artifacts, root, topology, policy, *, manifest=None, configuration_revision=None, **gates):
    """Deterministic Standard Profile projection; no duplicate business authority."""
    if type(artifacts) is not list: raise ValueError('semantic artifacts list required')
    _config(topology, policy)
    for artifact in artifacts: validate_artifact(artifact, root, topology, policy, **gates)
    unique([artifact['source_producer'] + '.' + artifact['id'] for artifact in artifacts], 'projection artifact')
    ordered = sorted(artifacts, key=lambda a: (a['source_producer'], a['id']))
    if manifest is not None: validate_manifest(manifest)
    revision = manifest['revision'] if manifest is not None else ordered[0]['revision'] if ordered else configuration_revision
    config_refs = _configuration_refs(root, topology, policy, revision)
    sections = {name: {'status': 'UNKNOWN', 'records': [], 'references': []} for name in PROFILE['sections']}
    if manifest is not None:
        validate_manifest(manifest)
        if manifest['authority'] != SEMANTIC_OWNERS: raise ValueError('Foundation semantic ownership drift')
        for domain, ref in manifest['entry_points'].items():
            if ref['path'] != policy['authority'].get(domain): raise ValueError('policy authority mismatch')
            _declared_ref(root, topology, ref)
        for name, row in manifest['sections'].items():
            if row['owner'] != SEMANTIC_OWNERS[SECTION_DOMAINS[name]]: raise ValueError('section ownership drift')
            for ref in row['references']:
                _declared_ref(root, topology, ref)
                if row['evidence'] == 'CONFIRMED':
                    auth = gates.get('authority_authenticator')
                    domain = SECTION_DOMAINS[name]
                    if ref['path'] != policy['authority'][domain] or not callable(auth) or auth(domain, copy.deepcopy(ref)) is not True:
                        raise ValueError('unauthenticated CONFIRMED manifest section')
            sections[name].update(status=row['status'], references=copy.deepcopy(row['references']), evidence_label=row['evidence'])
        if any(row['evidence'] == 'APPROVED_TARGET' for row in manifest['sections'].values()):
            context = gates.get('approval_context') or {}
            if context.get('manifest') != manifest: raise ValueError('exact approved manifest context required')
            _approval(manifest, root, context.get('approval'), context.get('human_actor_authenticator'), context.get('previous'))
    for artifact in ordered:
        for row in sorted(artifact['records'], key=lambda r: r['id']):
            if artifact['source_producer'] == 'adr-management': name = 'architecture_decisions'
            elif artifact['source_producer'] == 'c4-modeling': name = 'building_block_view'
            else: name = ARC42_TOPICS.get(row['topic'])
            if name is None: continue  # Business-rule candidates stay with BA.
            if name == 'introduction_goals' and row['evidence_label'] not in ('CONFIRMED', 'APPROVED_TARGET', 'UNKNOWN', 'DEFERRED'):
                continue
            entry = copy.deepcopy(row)
            entry.update(artifact_id=artifact['id'], artifact_revision=artifact['revision'])
            if name == 'introduction_goals': entry['statement'] = 'Product goals: consult exact BA-owned source.'
            if artifact['source_producer'] == 'adr-management': entry['decision_status'] = artifact['decision_status']
            sections[name]['records'].append(entry)
    lines = ['# arc42 Standard Profile', '', 'Artifact class: DERIVED. Generation does not approve this projection.', '']
    for name, title in zip(PROFILE['sections'], PROFILE['section_titles']):
        section = sections[name]
        rows = section['records']
        if manifest is None and rows:
            section['status'] = 'UNKNOWN' if all(row['evidence_label'] == 'UNKNOWN' for row in rows) else 'PARTIAL'
        lines.extend(['## ' + title, '', 'Status: ' + section['status'], ''])
        if section['references']: lines.extend(['Manifest references: ' + json.dumps(section['references'], sort_keys=True), ''])
        if not rows: lines.extend(['UNKNOWN: no validated semantic content supplied.', ''])
        # JSON fenced records keep evidence labels, owner and open questions visible.
        for row in rows:
            lines.extend(['```json', json.dumps(row, sort_keys=True, ensure_ascii=True).replace('`', '\\u0060'), '```', ''])
    return _view('ARC42_STANDARD_MARKDOWN', {'artifacts': ordered, 'manifest': manifest, 'config_refs': config_refs},
                 '\n'.join(lines), sections=sections, input_references=config_refs)


def conflicts(artifacts, disagreements, root, topology, policy, **gates):
    """Caller-declared competing meanings; no model-preference source ranking.

    BA authority preference applies only to business meaning. All conflicts stay
    UNRESOLVED; no assertion is dropped or silently promoted.
    """
    validate_schema(disagreements, {'type': 'array', 'items': object_schema({
        'domain': ENUM(('product', 'domain', 'architecture', 'testing')),
        'claims': {'type': 'array', 'minItems': 2, 'items': object_schema({'producer': ENUM(PRODUCERS), 'record_id': STRING})}})})
    reject_secrets(disagreements)
    lookup = {}
    for artifact in artifacts:
        validate_artifact(artifact, root, topology, policy, **gates)
        for row in artifact['records']:
            key = (artifact['source_producer'], row['id'])
            if key in lookup: raise ValueError('ambiguous conflict claim identity')
            lookup[key] = row
    result = []
    for disagreement in disagreements:
        claims = sorted(disagreement['claims'], key=lambda c: (c['producer'], c['record_id']))
        unique([claim['producer'] + '.' + claim['record_id'] for claim in claims], 'conflict claim')
        rows = []
        for claim in claims:
            key = (claim['producer'], claim['record_id'])
            if key not in lookup: raise ValueError('unknown competing claim')
            rows.append(lookup[key])
        refs = {semantic_bytes(ref): ref for row in rows for ref in row['references']}
        if any(not row['references'] and row['evidence_label'] not in ('PROPOSED', 'UNKNOWN') for row in rows):
            raise ValueError('conflict factual claim needs evidence')
        preferred = [claim for claim, row in zip(claims, rows) if row['owner'] == 'BA'
                     and row['evidence_label'] in ('CONFIRMED', 'APPROVED_TARGET')]
        value = {'domain': disagreement['domain'], 'claims': claims,
                 'references': [copy.deepcopy(refs[key]) for key in sorted(refs)],
                 'evidence_labels': [row['evidence_label'] for row in rows], 'status': 'UNRESOLVED',
                 'preferred_claim': preferred[0] if disagreement['domain'] in ('product', 'domain') and len(preferred) == 1 else None}
        value['id'] = 'conflict-' + hashlib.sha256(semantic_bytes(value)).hexdigest()[:20]
        result.append(value)
    unique([row['id'] for row in result], 'conflict id')
    return sorted(result, key=lambda row: row['id'])
